### PR TITLE
Add support to always show given keys of an object that has diffs

### PR DESCRIPTION
**Pull request by pablomatiasgomez**
This adds a new functionality to always show the given object keys (with their value) if the object has any diff.

For example, having the following json:

a.json
```json
{
  "foo": 10,
  "bar": 15
}
```

b.json
```json
{
  "foo": 10,
  "bar": 49
}
```

If you run `json-diff.js --show-keys foo a.json b.json`, you get:
```
 {
   foo: 10
-  bar: 15
+  bar: 49
 }
```

If you run it without show-keys, like: `json-diff.js a.json b.json`, you get:

```
 {
-  bar: 15
+  bar: 49
 }
```

### CODE REVIEW

**Comment by ryantheleach** [comment]
This would be really handy, so you can get a list of id's as well as human readable names.

**Comment by ewoudenberg** [comment]
Hi Pablo,

There is a new option in v0.6.0 called "--full" that outputs the entire JSON document, even the parts that are the same.  While I think your feature is useful, it is to some extent subsumed by the --full option, so I am closing this request. If you still feel your feature is necessary, please make a new PR against the ES6 version of the library. Thanks!

**Comment by ryantheleach** [comment]
The main usecase for me, was pinning the key 'id' so I know which object changed in a long list.

This will work, but it mildly feels like having the whole document somewhat defeats the purpose of the diff.

**Comment by pablomatiasgomez** [comment]
@ryantheleach Exactly, I used it for the same purpose, and printing the entire json won't be useful for me. I will probably create a new PR against the ES6 version, if maintainers are willing to approve/merge it

**Comment by pablomatiasgomez** [comment]
Hi @ewoudenberg thanks for the feedback, I just opened a new pull request against the latest code https://github.com/andreyvit/json-diff/pull/72 which I hope could be merged. Let's follow up on that PR if you have any concerns. Thanks!

**Pull request closed without merging**
