### PR TITLE
Adds new CLI option and parameter to specify keys which should be excluded 

### PR DESCRIPTION
**Pull request by karlitos**

### CODE REVIEW

**Comment by karlitos** [comment]
Can you look at this ? I was not yet able to test this, getting error when trying to run `bin/json-diff.js`
```bash
/Users/Karel.Macha@tui.com/Dev/Tui/json-diff/node_modules/dreamopt/lib/dreamopt.js:830
      throw new Error("Invalid option spec format (cannot parse " + (JSON.stringify(options)) + "): " + (JSON.stringify(spec)));
      ^

Error: Invalid option spec format (cannot parse "--exclude-keys KEYS Exclude this comma separated keys from comparison on both files #var(excludeKeys)"): "-x, --exclude-keys KEYS Exclude this comma separated keys from comparison on both files #var(excludeKeys)"
    at Function.Option.parse (/Users/Karel.Macha@tui.com/Dev/Tui/json-diff/node_modules/dreamopt/lib/dreamopt.js:830:13)
    at Syntax.add (/Users/Karel.Macha@tui.com/Dev/Tui/json-diff/node_modules/dreamopt/lib/dreamopt.js:470:46)
    at parse (/Users/Karel.Macha@tui.com/Dev/Tui/json-diff/node_modules/dreamopt/lib/dreamopt.js:866:12)
    at module.exports (/Users/Karel.Macha@tui.com/Dev/Tui/json-diff/lib/cli.js:8:38)
    at Object.<anonymous> (/Users/Karel.Macha@tui.com/Dev/Tui/json-diff/bin/json-diff.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```
I was not able to find out what I am doing wrong with the _dreampot_ options

**Comment by karlitos** [comment]
I resolved my issues with the `dreampot`, it turned out, that there needs to be at least two spaces before the description. It works pretty good, I will now start testing and try to write some more tests

**Comment by ewoudenberg** [comment]
Very nice Karel, thank you!

**Comment by karlitos** [comment]
You are welcome, I think we might now close #36 and #83

**Comment by denes16** [comment]
Can i use this in the nodejs version?

**Comment by karlitos** [comment]
> Can i use this in the nodejs version?

If you mean whether  you can use this programatically and not via CLI, the answer is yes. Take a look at some of the [unit-test I created](https://github.com/andreyvit/json-diff/blob/35582a9d19f8b0b2773360d67937e57ce2866781/test/diff_test.coffee#L225).

**Pull request merged**
